service: presigned-s3-upload

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - Fn::Join:
            - ""
            - - "arn:aws:s3:::"
              - Ref: "SignedUploadBucket"
              - "/*"
  environment:
    BUCKET_NAME:
      Ref: SignedUploadBucket

functions:
  sign-url:
    handler: url-signer.sign
    events:
      - http:
          path: /signed-url
          method: get
          cors: true

  sign-post:
    handler: post-signer.sign
    events:
      - http:
          path: /signed-post
          method: get
          cors: true


  start-upload:
    handler: post-multipart.startUpload
    events:
      - http:
          path: /start-multipart-upload
          method: get
          cors: true

  get-upload-url:
    handler: post-multipart.getUploadUrl
    events:
      - http:
          path: /get-multipart-upload-url
          method: get
          cors: true

  complete-upload:
    handler: post-multipart.completeUpload
    events:
      - http:
          path: /complete-multipart-url
          method: get
          cors: true

resources:
  Resources:
    SignedUploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - PUT
                - POST
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
